# Generated by Django 4.1 on 2022-09-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_user', models.CharField(max_length=30)),
                ('apellido_user', models.CharField(max_length=30)),
                ('correo_user', models.CharField(max_length=50)),
                ('contraseña_user', models.CharField(max_length=30)),
            ],
        ),
    ]
