# Generated by Django 4.1 on 2022-09-05 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='correo_user',
            field=models.EmailField(max_length=50),
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_culti', models.ImageField(upload_to='api')),
                ('nombre_culti', models.CharField(max_length=30)),
                ('nombre_scie_culti', models.CharField(max_length=30)),
                ('descripcion_culti', models.TextField(max_length=600)),
                ('tiempo_germinacion', models.IntegerField()),
                ('tiempo_cosecha', models.IntegerField()),
                ('tiempo_siembra', models.CharField(max_length=15)),
                ('tiempo_sol_culti', models.CharField(max_length=20)),
                ('cantidad_riego_culti', models.CharField(max_length=30)),
                ('distancia_plantas', models.IntegerField()),
                ('altura_max_culti', models.IntegerField()),
                ('tipo_recipiente', models.CharField(max_length=30)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
